name: Update Discoverygarden Composer Modules
author: discoverygarden
description: Updates composer with latest versions of discoverygarden modules.

inputs:
  composer-auth:
    description: 'Composer auth token necessary for accessing our composer project.'
    required: false
  github-token:
    description: The github token.
    required: true
outputs:
  updates:
    description: 'Indicates if any modules were updated.'

runs:
  using: composite
  steps:
    - name: Installing composer requirements
      shell: bash
      run: |
        # Configure access if necessary.
        if [ -n "${{ inputs.composer-auth }}" ] ; then
          echo '${{ inputs.composer-auth }}' > auth.json
        fi
    - name: Running upgrade
      id: upgrade
      shell: bash
      run: >
        composer outdated -D -m --locked --format=json
        | jq '.locked[] | select(.name | startswith("discoverygarden/")) | .name' -r
        | xargs -I {} -n1 composer update {} --with-dependencies
    - name: Confirm there are changes
      id: confirm
      shell: bash
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          echo "updates=true" >> "$GITHUB_OUTPUT";
        fi
